get_page_extract:
  fields:
    device_id:
      selector:
        device:
          integration: ha_mediawiki
    page_name:
      required: true
      example: "Home Assistant"
      default: ""
      selector:
        text:
